#!/bin/bash
message(){
  echo ""
  echo "$1"
  echo ""
}

clear

message "Create a temporary directory for Wordpress"
mkdir wp

message "Downloading the latest version of wordpress"
wget -P ./wp http://wordpress.org/latest.zip

message "Unzip the files"
cd wp
unzip latest.zip

clear
message "Remove wp-content folder"
# Go to the Wordpress directory
cd wordpress
# Remove wp-content directory
rm -rf wp-content
# Return to the temp directory wp/
cd ..

clear
message "Move all files to the current directory"
# Return to the paren (current) directory
cd ..
cp -R wp/wordpress/ .

message "Remove temp directory"
rm -rf ./wp

clear
message "Create a directory to store plugins"
mkdir wp-content/plugins/

rm -rf Moxie-Lean-master

cd ./<%= themePath %>
./bin/setup.sh

 cd ../../../
 rm script.sh
